repositoryUrlMobile: https://github.com/dynamsoft-docs/barcode-reader-docs-mobile/blob/main
repository: dynamsoft-docs/barcode-reader-docs-mobile
docFullPath: https://www.dynamsoft.com/barcode-reader/docs/mobile/
firstLevelUrl: /barcode-reader/docs/mobile
docHomePage: /barcode-reader/docs/core/introduction/

useVersionTree: true

features: /barcode-reader/docs/core/programming/features/
usecases: /barcode-reader/docs/core/programming/usecases/
introduction: /barcode-reader/docs/core/introduction/
programming: /barcode-reader/docs/core/programming/
parameters: /barcode-reader/docs/core/parameters/
license_activation: /barcode-reader/docs/core/license-activation/
release_notes: /barcode-reader/docs/core/release-notes/
performance: /barcode-reader/docs/core/performance/
faq: /barcode-reader/docs/core/faq/
faq_general: /barcode-reader/docs/core/faq/general/

faq_ios: /barcode-reader/docs/mobile/programming/objectivec-swift/faq/
faq_android: /barcode-reader/docs/mobile/programming/android/faq/

oc: /barcode-reader/docs/mobile/programming/objectivec-swift/
oc_api: /barcode-reader/docs/mobile/programming/objectivec-swift/api-reference/
oc_release_notes: /barcode-reader/docs/mobile/programming/objectivec-swift/release-notes/
oc_methods: /barcode-reader/docs/mobile/programming/objectivec-swift/api-reference/methods/
oc_class: /barcode-reader/docs/mobile/programming/objectivec-swift/api-reference/class/
oc_methods: /barcode-reader/docs/mobile/programming/objectivec-swift/api-reference/methods/
oc_faq: /barcode-reader/docs/mobile/programming/objectivec-swift/faq/

android: /barcode-reader/docs/mobile/programming/android/
android_api: /barcode-reader/docs/mobile/programming/android/api-reference/
android_release_notes: /barcode-reader/docs/mobile/programming/android/release-notes/
android_class: /barcode-reader/docs/mobile/programming/android/api-reference/class/
android_methods: /barcode-reader/docs/mobile/programming/android/api-reference/BarcodeReader/
android_faq: /barcode-reader/docs/mobile/programming/android/faq/

flutter: /capture-vision/docs/mobile/programming/flutter/
flutter_api: /capture-vision/docs/mobile/programming/flutter/api-reference/
flutter_local: /barcode-reader/docs/mobile/programming/flutter/

xamarin: /capture-vision/docs/mobile/programming/xamarin/
xamarin_api: /capture-vision/docs/mobile/programming/xamarin/api-reference/

cordova: /capture-vision/docs/mobile/programming/cordova/
cordova_api: /capture-vision/docs/mobile/programming/cordova/api-reference/

react_native: /capture-vision/docs/mobile/programming/react-native/
react_native_api: /capture-vision/docs/mobile/programming/react-native/api-reference/

dbr_android_api: /barcode-reader/docs/mobile/programming/android/api-reference/
dcv_android_api: /capture-vision/docs-archive/mobile/programming/android/api-reference/
dcvb_android_api: /capture-vision/docs/mobile/programming/android/api-reference/

dbr_ios_api: /barcode-reader/docs/mobile/programming/objectivec-swift/api-reference/
dcv_ios_api: /capture-vision/docs-archive/mobile/programming/ios/api-reference/
dcvb_ios_api: /capture-vision/docs/mobile/programming/ios/api-reference/

dbr_maui: /barcode-reader/docs/mobile/programming/maui/
dbr_maui_api: /barcode-reader/docs/mobile/programming/maui/api-reference/
dcv_maui: /capture-vision/docs/mobile/programming/maui/
dcv_maui_api: /capture-vision/docs/mobile/programming/maui/api-reference/
dce_maui: /camera-enhancer/docs/mobile/programming/maui/
dce_maui_api: /camera-enhancer/docs/mobile/programming/maui/api-reference/
dcp_maui: /code-parser/docs/mobile/programming/maui/
dcp_maui_api: /code-parser/docs/mobile/programming/maui/api-reference/

dcv_enumerations: /capture-vision/docs-archive/core/enums/
dcv_parameters_reference: /capture-vision/docs-archive/core/parameters/reference/
dcv_introduction: /capture-vision/docs-archive/core/introduction/
dcvb_enumerations: /capture-vision/docs/core/enums/
dcvb_parameters_reference: /capture-vision/docs/core/parameters/reference/
dcvb_introduction: /capture-vision/docs/core/introduction/
dcvb_architecture: /capture-vision/docs/core/architecture/
dcvb_parameters: /capture-vision/docs/core/parameters/

mobile_enum: /barcode-reader/docs/mobile/programming/enumeration/

parameters_reference: /barcode-reader/docs/core/parameters/reference/
image_parameters: /barcode-reader/docs/core/parameters/reference/image-parameter/
scenario_settings: /barcode-reader/docs/core/parameters/scenario-settings/
enumerations: /barcode-reader/docs/core/web/parameters/enum/

understanding: /barcode-reader/docs/core/web/understanding/

assets: /barcode-reader/docs/mobile/assets/
edit_icon: /barcode-reader/docs/mobile/assets/img-icon/edit-icon.png
smile_icon: /barcode-reader/docs/mobile/assets/img-icon/icon-smile.png
sad_icon: /barcode-reader/docs/mobile/assets/img-icon/icon-sad.png
dbr_icon: /barcode-reader/docs/mobile/assets/img-icon/icon-dbr.svg
dwt_icon: /barcode-reader/docs/mobile/assets/img-icon/icon-dwt.svg
dnt_icon: /barcode-reader/docs/mobile/assets/img-icon/icon-dnt.svg

dce_android: /camera-enhancer/docs/mobile/programming/android/
dce_ios: /camera-enhancer/docs/mobile/programming/ios/
dce_enumerations: /camera-enhancer/docs/core/enums/

dcp_android: /code-parser/docs/mobile/programming/android/
dcp_android_api: /code-parser/docs/mobile/programming/android/api-reference/
dcp_ios: /code-parser/docs/mobile/programming/ios/
dcp_ios_api: /code-parser/docs/mobile/programming/ios/api-reference/

baseurl: "/barcode-reader/docs/mobile"
plugins:
  - jemoji
  - jekyll-webp
  - jekyll-relative-links
  - jekyll-redirect-from
  - jekyll-readme-index
  - jekyll-seo-tag

edition: mobile

defaults:
  - scope:
      path: ""
    values:
      category: "original-repo"
      edition: "algorithm"
  - scope:
      path: "programming/android"
    values:
      category: "mobile-repo"
      edition: "mobile"
      docRootName: "Barcode Reader Android Edition" 
      docHomePage: "/barcode-reader/docs/mobile/programming/android/"
  - scope:
      path: "programming-old/android"
    values:
      category: "mobile-repo"
      edition: "mobile"
      docRootName: "Barcode Reader Android Edition" 
      docHomePage: "/barcode-reader/docs/mobile/programming/android/"
  - scope:
      path: "programming/objectivec-swift"
    values:
      category: "mobile-repo"
      edition: "mobile"
      docRootName: "Barcode Reader iOS Edition" 
      docHomePage: "/barcode-reader/docs/mobile/programming/objectivec-swift/"
  - scope:
      path: "programming-old/objectivec-swift"
    values:
      category: "mobile-repo"
      edition: "mobile"
      docRootName: "Barcode Reader iOS Edition" 
      docHomePage: "/barcode-reader/docs/mobile/programming/objectivec-swift/"
  - scope:
      path: "programming/flutter"
    values:
      category: "mobile-repo"
      edition: "mobile"
      docRootName: "Barcode Reader Flutter Edition" 
      docHomePage: "/capture-vision/docs/mobile/programming/flutter/"
  - scope:
      path: "programming/react-native"
    values:
      category: "mobile-repo"
      edition: "mobile"
      docRootName: "Barcode Reader React Native Edition" 
      docHomePage: "/capture-vision/docs/mobile/programming/react-native/"
  - scope:
      path: "programming/cordova"
    values:
      category: "mobile-repo"
      edition: "mobile"
      docRootName: "Barcode Reader Cordova Edition" 
      docHomePage: "/capture-vision/docs/mobile/programming/cordova/"
  - scope:
      path: "programming/xamarin"
    values:
      category: "mobile-repo"
      edition: "mobile"
      docRootName: "Barcode Reader Xamarin.Forms Edition" 
      docHomePage: "/capture-vision/docs/mobile/programming/xamarin/"
  - scope:
      path: "programming/maui"
    values:
      category: "mobile-repo"
      edition: "mobile"
      docRootName: "Barcode Reader MAUI Edition" 
      docHomePage: "/barcode-reader/docs/mobile/programming/maui/"
  - scope:
      path: "programming/enumeration"
    values:
      category: "mobile-repo"
      edition: "mobile"
      docRootName: "Barcode Reader Enumerations"
      docHomePage: "/barcode-reader/docs/mobile/programming/enumeration/"
  - scope:
      path: "programming-old/enumeration"
    values:
      category: "mobile-repo"
      edition: "mobile"
      docRootName: "Barcode Reader Enumerations"
      docHomePage: "/barcode-reader/docs/mobile/programming/enumeration/"
  - scope:
      path: ""
    values:
      layout: "default-layout"
      noTitleIndex: true
      needAutoGenerateSidebar: true
      needGenerateH3Content: true

url: "https://www.dynamsoft.com" # sitemap root
